// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // prisma migrate deploy needs a direct (non-pooled) connection for DDL.
    // POSTGRES_URL_NON_POOLING bypasses PgBouncer; POSTGRES_PRISMA_URL hangs on DDL.
    url: process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["DATABASE_URL"],
  },
});
